name: smaSDK
description: SDK for the DIJ SMA API
# version: 1.0.0
# homepage: https://www.example.com
# author: Jordy van Domselaar <jordy.m.van.domselaar@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0

dev_dependencies:
  test: ^1.0.0
